name: auto-merge-readme

on:
    pull_request:
        branches: [main]
        types: [opened]

permissions:
    pull-requests: write
    contents: write

jobs:
    auto-merge:
        runs-on: ubuntu-latest
        if: github.event.pull_request.user.login == 'oimurat'
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GITHUB_PAT: ${{ secrets.REPO_ACCESS_TOKEN }}
        steps:
            - name: Checkout repository with preceding commits
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check if only README.md is updated
              run: |
                  git diff --name-only "origin/main" HEAD | tee /tmp/diffs
                  if [ "$(wc -l < /tmp/diffs)" -eq "$(grep -c "^README.md$" /tmp/diffs)" ]; then
                    echo 'ONLY_README=yes' | tee -a "$GITHUB_ENV"
                  else
                    echo 'ONLY_README=no' | tee -a "$GITHUB_ENV"
                  fi

            - name: Authenticate Github CLI with PAT
              run: echo "$GITHUB_PAT" | gh auth login --with-token

            # - name: Approve PR
            #   if: env.ONLY_README == 'yes'
            #   run: gh pr review "$PR_URL" --approve

            - name: Enable auto-merge
              if: env.ONLY_README == 'yes'
              run: gh pr merge --merge --auto "$PR_URL"
